nginx:
  build: images/nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "80:80"
php:
  build: images/php
  volumes:
    - ./images/php:/var/www/html
  working_dir: /var/www/html/app/public
  command: php-fpm
  links:
    - billingsdb
    - cache
  ports:
    - "9000:9000"
  environment:
    APP_ENV: local
    APP_DEBUG: 'true'
    APP_KEY: 1Bj7POHGkoKmxppwkyqSVTUYEzzTlDjT
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    DB_CONNECTION: mysql
    DB_HOST: billingsdb
    DB_DATABASE: billings
    DB_USERNAME: root
    DB_PASSWORD:
    MEMCACHED_HOST: cache
    CACHE_DRIVER: memcached
billingsdb:
  image: mysql
  container_name: billing
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD:
    MYSQL_DATABASE: billings
    MYSQL_USER: root
    MYSQL_PASSWORD:
cache:
  image: memcached
